name: conealign_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - certifi=2020.6.20
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - pip=19.3.1
  - python=2.7.18
  - readline=8.2
  - setuptools=44.0.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.37.1
  - zlib=1.2.13
  - pip:
      - cython==3.0.12
      - decorator==4.4.2
      - networkx==2.2
      - numpy==1.16.6
      - pot==0.7.0
      - scikit-learn==0.20.4
      - scipy==1.2.3
      - six==1.17.0
      - theano==1.0.5
